idea_data = [
    {
        "name": "Artificial Intelligence-Driven Document Analysis",
        "domain": ["Phần mềm (Software)"],
        "slogan": "Proof of concept leading to scale-up, joint development, supplier agreement, licensing.",
        "problem": "The Ministry of Labor of Qatar seeks to digitalize the document analysis process by adopting AI-driven technologies that offer a high level of automation, accuracy, and security. They are seeking a custom made, multi-language solution that leverages advanced Artificial Intelligence and Natural Language Processing capabilities to ensure compliance with Qatari Labour law.",
        "solution": "The Ministry of Labor (MoL) in Qatar plays a crucial role in shaping labor policies and regulations. MoL handles a substantial volume of contracts and documents associated with employment, labor laws, and business operations. Ensuring the compliance of these documents with established procedures and Qatari Labour law is of paramount importance to uphold fairness, protect workers' rights, and maintain a healthy labor environment. Document analysis is a critical procedure for MoL as it enables them to monitor and validate the legality of contracts, assess potential risks, and ensure that all parties involved adhere to the relevant labor laws. Manual document analysis has proven to be time-consuming, labor-intensive, and prone to errors, leading to delays in processing and potential oversights.",
        "teamDescription": "<5 thành viên",
        "teamExperience": "",
        "gender": "Global",
        "ageRange": [0, 54],
        "professional": ["Mọi người"],
        "geographical": ["Vietnam"],
        "behavior": "Implementation of an efficient and secure Contract Management System that uses a combination of advanced AI and NLP technologies",
        "apps": "Non-smart contract analysis based solutions\\nSolutions that do not work or have not potential to work with the Arabic language\\nLow TRL solutions",
        "outstand": "Joint Development Technology Acquisition Technology Licensing To Be Negotiated",
        "currentDev": "[Ý tưởng] Ý tưởng chưa được thực hiện",
        "support": "",
        "files": [
            "656085987981d95b28f942a7/tu-tuong-ho-chi-minh__van-dung-tu-tuong-dai-doan-ket-dan-toc-cua-ho-chi-minh-vao-xay-dung-tinh-thandoan-ket-trong-sinh-vien-dai-hoc-bach-khoa-ha-noi - [cuuduongthancong.com].pdf"
        ],
        "innovator_id": "66499608bc5feffef11b1b31",
    },
    {
        "name": "Licensing and Establishing a DMS, DMDS Manufacturing Process",
        "domain": ["Dịch vụ chuyên nghiệp (Professional Services)"],
        "slogan": "Technology Licensing; Technology Acquisition, Turnkey solution; Supplier agreement; Consulting",
        "problem": "Licensing and Establishing a DMS, DMDS Manufacturing Process\\n",
        "solution": "NineSigma, representing a large industrial company, is seeking organizations that can support with the establishment of high purity dimethyl sulfide (DMS) and/ or dimethyl disulfide (DMDS) production facilities at scales of minimally 1000 metric tons annually.",
        "teamDescription": "<20 thành viên",
        "teamExperience": "",
        "gender": "Male",
        "ageRange": [0, 20],
        "professional": ["Doanh nghiệp"],
        "geographical": ["Asia"],
        "behavior": "Organizations who can license the technology\\nOrganizations with turn-key solutions\\nOrganizations who can share relevant know-how to establish the production facility\\nExperts who can advise to establish the production facility\\nSecond priority: Organizations who can supply high quality (>99% purity) DMS /DMDS globally",
        "apps": "Organizations with processes that cannot meet the minimum purity of >99%.",
        "outstand": "ConsultingSupply AgreementTechnology AcquisitionTechnology LicensingTo Be Negotiated",
        "currentDev": "[Hiện thực] Ý tưởng đang được hiện thực và thử nghiệm trong môi trường phát triển",
        "support": "",
        "files": ["656098e48287b361ff02f953/A3_230315.pdf"],
        "innovator_id": "66499608bc5feffef11b1b31",
    },
    {
        "name": "Thúc đẩy chuyển đổi xanh trong thời đại công nghệ 4.0",
        "domain": ["Năng lượng (Energy)"],
        "slogan": "Sản xuất xanh và phát triển bền vững",
        "problem": "Những chiến lược và cơ chế lãnh đạo nào có thể hỗ trợ hiệu quả cho hoạt động đồng sáng tạo, học hỏi và đổi mới theo hướng chuyển đổi xanh?",
        "solution": "Nghiên cứu sẽ dựa trên các nghiên cứu điển hình và các hành động đồng sáng tạo ở các thành phố Oslo, Gothenburg và Copenhagen. Hơn nữa, GREENGOV sẽ tạo điều kiện thuận lợi cho hoạt động học tập mang tính đột phá bằng cách đưa ra các ví dụ về khả năng lãnh đạo đồng sáng tạo từ Cape Town; một thành phố đầy tham vọng nhưng khác biệt về các hoạt động và chính sách khí hậu. Mistra Urban Futures sẽ đặc biệt tham gia vào nghiên cứu điển hình ở Gothenburg và phát triển lý thuyết.\\n\\nDự án sẽ kết hợp nghiên cứu xuyên ngành với 'CityLabs', dự án sẽ hoạt động như các thử nghiệm thiết kế để điều tra xem các can thiệp lãnh đạo khác nhau ảnh hưởng như thế nào đến hoạt động đồng sáng tạo xanh trong các bối cảnh khác nhau.\\n\\nTrong các thành phố nghiên cứu điển hình, chúng tôi xác định và so sánh các mô hình quản trị của chúng nhằm thúc đẩy hơn nữa sự chuyển đổi xanh trong các bối cảnh chính trị và quản trị khác nhau: trong thành phố; trong khu vực đô thị và quốc gia rộng lớn hơn; và trong mối quan hệ giữa thành phố với thành phố",
        "teamDescription": "<5 thành viên",
        "teamExperience": "Nhóm được lãnh đạo bởi Viện Nghiên cứu Đô thị và Khu vực Na Uy (NIBR) tại Đại học Thủ đô Oslo do Tiến sĩ Hege Hofstad (trưởng nhóm) đại diện; Trond Vedeld, Tiến sĩ; Tiến sĩ Marianne Millstein; Geir Heierstad, Tiến sĩ; Jan-Tore Berghei, MA; và Gro Sandkjær Hanssen, Tiến sĩ.",
        "gender": "Male",
        "ageRange": [0, 47],
        "professional": ["Học sinh, sinh viên", "Doanh nghiệp", "Người tiêu dùng"],
        "geographical": ["Vietnam"],
        "behavior": "Chúng tôi bắt đầu từ tiền đề rằng thách thức cấp bách nhất đối với các thành phố liên quan đến 'sự chuyển đổi xanh' không phải là việc tìm kiếm các giải pháp công nghệ phù hợp mà là tìm ra những cách thức mới để quản lý quá trình chuyển đổi hướng tới tương lai thông minh về khí hậu, tiết kiệm năng lượng, toàn diện, kiên cường và bền vững. . Tuy nhiên, các cấu trúc và hệ thống thông thường của khu vực công không được thiết lập để giải quyết các nhiệm vụ về khái niệm hóa, lập bản đồ và giải quyết các vấn đề có mức độ phức tạp cao như vậy.",
        "apps": "1. Đóng góp kiến thức tiên tiến về lãnh đạo đồng sáng tạo như một phương tiện để nâng cao năng lực quản lý quá trình chuyển đổi xanh, thông qua nghiên cứu xuyên ngành và học tập chung trong các lĩnh vực đồng sáng tạo ('CityLabs').\\n2. Dự án sẽ phát triển kiến thức và bài học chính sách về “kinh nghiệm của Scandinavia” trong việc quản lý chuyển đổi xanh ở cấp thành phố – so sánh năng lực lãnh đạo, học tập và đổi mới đồng sáng tạo ở các thành phố Oslo, Copenhagen và Gothenburg.",
        "outstand": "Cụ thể hơn, chúng tôi quan tâm đến cách các thành phố có thể xây dựng các đấu trường đồng sáng tạo và thông qua những đấu trường này nâng cao năng lực của họ trong việc tạo ra sự phối hợp giữa các lớp thể chế của các biện pháp mạng lưới, lấy cảm hứng từ thị trường và phân cấp cùng nhau tạo nên các cơ chế quản trị dành cho các nhà lãnh đạo chính trị và hành chính khi phấn đấu chuyển đổi carbon thấp bền vững.",
        "currentDev": "[Ý tưởng] Ý tưởng chưa được thực hiện",
        "support": "Về tài chính, chúng tôi cần hỗ trợ tài chính để xây dựng hệ thống từ giai đoạn ban đầu của ý tưởng",
        "files": ["6564a720fe8eec62f4140b47/Mô tả BTL2.pdf"],
        "innovator_id": "65f4602b14c88ec7dd8dd787",
    },
    {
        "name": "Sàn kết nối ý tưởng với doanh nghiệp",
        "domain": ["Phần mềm (Software)"],
        "slogan": "Ý tưởng không còn là ý tưởng",
        "problem": "Những hệ thống đăng tải ý tưởng ngày nay chưa đáp ứng đủ nhu cầu của nhà sáng tạo. Các ý tưởng đăng lên nhưng không quá chú trọng về nội dung mà chỉ quan tâm đến số lượng.",
        "solution": "Hiện thực một hệ thống mới giúp người dùng có thể đăng tải những ý tưởng sáng kiến của bản thân về một vấn đề gì đó trong cuộc sống. Ở đây, các ý tưởng với độ hoàn thiện và được đánh giá cao sẽ có khả năng lớn trong việc kết hợp với doanh nghiệp trong ngành liên quan",
        "teamDescription": "<5 thành viên",
        "teamExperience": "Có kinh nghiệm trong việc xây dựng hệ thống. Có kiến thức về xử lý ngôn ngữ tự nhiên",
        "gender": "Male",
        "ageRange": [0, 29],
        "professional": ["Mọi người"],
        "geographical": ["Vietnam"],
        "behavior": "Sàn ý tưởng giúp thu hẹp khoảng cách giữa ý tưởng và thực tế. Thông qua việc kết nối với doanh nghiệp, nhà sáng tạo có thể cơ hội, học hỏi thêm kinh nghiệm và những góp ý từ phía doanh nghiệp",
        "apps": "ytuongsangtao.net, ytuongsangtaohcm Quá nhiều ý tưởng, tuy nhiên nội dung ý tưởng không chất lượng",
        "outstand": ["Ứng dụng cao"],
        "currentDev": "[Hiện thực] Ý tưởng đang được hiện thực và thử nghiệm trong môi trường phát triển",
        "support": "",
        "innovator_id": "65f4602b14c88ec7dd8dd787",
        "files": []
    },
    {
        "name": "Bóng đèn nước",
        "domain": [
            "Năng lượng (Energy)",
            "Công nghệ sạch và Bền vững môi trường (Clean Tech and Environmental Sustainability)",
        ],
        "slogan": "Thắp ánh sáng cho người nghèo",
        "problem": "Ở rất nhiều nơi trên thế giới, điện vẫn là nguồn năng lượng xa xỉ đối với người nghèo. Tại những khu vực nông thôn, hay khu ổ chuột trong những thành phố lớn, hàng triệu gia đình vẫn phải tận dụng từng chút ánh sáng mặt trời được hứng từ những khe cửa sổ nhỏ.",
        "solution": "Hiện thực một hệ thống mới giúp người dùng có thể đăng tải những ý tưởng sáng kiến của bản thân về một vấn đề gì đó trong cuộc sống. Ở đây, các ý tưởng với độ hoàn thiện và được đánh giá cao sẽ có khả năng lớn trong việc kết hợp với doanh nghiệp trong ngành liên quan",
        "teamDescription": "Cá nhân",
        "teamExperience": "Chưa có kinh nghiệm",
        "gender": "Global",
        "ageRange": [0, 90],
        "professional": ["Mọi người"],
        "geographical": ["Vietnam"],
        "behavior": "Chỉ với nước, nước tẩy đựng trong một chiếc bình nhựa tái sử dụng, Alfredo Moser đã sáng tạo ra nguồn sáng tương đương độ sáng của bóng đèn 40 – 60 Watts. Cơ chế hoạt động của chiếc đèn nước rất đơn giản, chai đựng đầy nước được lắp đặt trên nóc nhà, một phần tiếp xúc trực tiếp với mặt trời, một phần tiếp xúc với không gian cần chiếu sáng. Chai nước như một thấu kính hội tụ tia sáng mặt trời, phản chiếu ánh sáng vào trong nhà.",
        "apps": "Một bóng đèn sợt đốt 50 watts nếu phát sáng 14 giờ/ngày, trong 1 năm sẽ tạo ra gần 200 kg khí CO2. Trong khi đó, bóng đèn nước của Moser không tạo ra khí thải cácbon. Việc tận dụng vỏ chai nước bỏ đi để làm đèn giúp giảm lượng rác thải, tiết kiệm chi phí thu hồi, xử lý  tái chế các chai nhựa. Sử dụng đèn nước của Moser không lo cháy nổ, giật điện, tiết kiệm được tiền điện chiếu sáng hàng ngày cho những hộ dân nghèo.",
        "outstand": ["Ứng dụng cao"],
        "currentDev": "[Hoàn thiện] Ý tưởng đã có thể đưa ra thị trường và hoạt động tốt",
        "support": "",
        "innovator_id": "65f4602b14c88ec7dd8dd787",
        "files": []
    },
    {
        "name": "Máy trợ thính giá",
        "domain": ["Thiết bị phần cứng và IoT", "Thiết bị Y tế"],
        "slogan": "Máy trợ thính giá hợp lý cho người nghèo",
        "problem": "Người dân Ấn Độ đã phải tốn số tiền không hề nhỏ khoảng 400-500 đôla khi hẹn gặp bác sĩ và 1.900 đôla để mua máy trợ thính. Tôi nhận thức được những chi phí này quá tốn kém so với thu nhập của người dân nên quyết định bắt tay vào chế tạo máy trợ thính giá rẻ.",
        "solution": "Thiết bị dài khoảng 5 cm, nhìn giống bộ xử lý máy tính và rất đặc biệt ở chỗ không những chỉ kiểm tra thính giác với loạt tiếng bíp, mà còn có chức năng trợ thính. Chiếc máy giá khoảng 50 đôla, rẻ gấp 38 lần máy trợ thính thông thường và có thể kết hợp cùng với loại tai nghe bình dân nhất. Nếu một phần trong tai nghe bị hỏng thì chỉ cần mua bộ tai nghe mới, rất tiện và kinh tế.",
        "teamDescription": "Cá nhân",
        "teamExperience": "Chưa có kinh nghiệm",
        "gender": "Global",
        "ageRange": [0, 90],
        "professional": ["Mọi người"],
        "geographical": ["Vietnam"],
        "behavior": "Mukund đã tự học về mật mã trong vòng suốt 2 năm, phát triển chương trình âm thanh và thiết bị dưới sự trợ giúp của bố và các nhà thính học. Bên cạnh đó, cậu cũng làm việc với các bác sĩ và thử nghiệm với bệnh nhân để đảm bảo thiết bị hoạt động tốt.",
        "apps": "Không có thông tin",
        "outstand": ["Ứng dụng cao"],
        "currentDev": "[Alpha] Ý tưởng đang được thử nghiệm trong môi trường thực tế nhưng chưa hoàn thiện",
        "support": "",
        "innovator_id": "65f4602b14c88ec7dd8dd787",
        "files": []
    },
    {
        "name": "Máy trợ thính giá",
        "domain": ["Thiết bị phần cứng và IoT", "Thiết bị Y tế"],
        "slogan": "Máy trợ thính giá hợp lý cho người nghèo",
        "problem": "Người dân Ấn Độ đã phải tốn số tiền không hề nhỏ khoảng 400-500 đôla khi hẹn gặp bác sĩ và 1.900 đôla để mua máy trợ thính. Tôi nhận thức được những chi phí này quá tốn kém so với thu nhập của người dân nên quyết định bắt tay vào chế tạo máy trợ thính giá rẻ.",
        "solution": "Thiết bị dài khoảng 5 cm, nhìn giống bộ xử lý máy tính và rất đặc biệt ở chỗ không những chỉ kiểm tra thính giác với loạt tiếng bíp, mà còn có chức năng trợ thính. Chiếc máy giá khoảng 50 đôla, rẻ gấp 38 lần máy trợ thính thông thường và có thể kết hợp cùng với loại tai nghe bình dân nhất. Nếu một phần trong tai nghe bị hỏng thì chỉ cần mua bộ tai nghe mới, rất tiện và kinh tế.",
        "teamDescription": "Cá nhân",
        "teamExperience": "Chưa có kinh nghiệm",
        "gender": "Global",
        "ageRange": [0, 90],
        "professional": ["Mọi người"],
        "geographical": ["Vietnam"],
        "behavior": "Mukund đã tự học về mật mã trong vòng suốt 2 năm, phát triển chương trình âm thanh và thiết bị dưới sự trợ giúp của bố và các nhà thính học. Bên cạnh đó, cậu cũng làm việc với các bác sĩ và thử nghiệm với bệnh nhân để đảm bảo thiết bị hoạt động tốt.",
        "apps": "Không có thông tin",
        "outstand": ["Ứng dụng cao"],
        "currentDev": "[Alpha] Ý tưởng đang được thử nghiệm trong môi trường thực tế nhưng chưa hoàn thiện",
        "support": "",
        "innovator_id": "65f4602b14c88ec7dd8dd787",
        "files": []
    },
    {
        "name": "Bàn Đứng Cho Văn Phòng",
        "domain": ["Hàng tiêu dùng (Consumer Goods)"],
        "slogan": "Bàn Đứng Cho Văn Phòng Tại Nhà",
        "problem": "Trong bối cảnh xu hướng làm việc từ xa ngày càng gia tăng, cộng thêm những thách thức do đại dịch đang diễn ra, việc tập trung vào sức khỏe cá nhân khi làm việc tại nhà trở thành trọng tâm. Giải pháp nằm ở những chiếc bàn đứng— một trong những ý tưởng khởi nghiệp sáng tạo không chỉ hỗ trợ các tiêu chuẩn làm việc lành mạnh hơn mà còn giải quyết những lo ngại nảy sinh từ việc ngồi lâu.",
        "solution": "Trước tiên, bạn cần tìm một nhà cung cấp bàn đứng cho phép bạn bán sản phẩm của họ tại địa phương. Kết nối với các doanh nghiệp và doanh nhân địa phương để giáo dục họ và nhân viên của họ về lợi ích của bàn đứng. Đưa ra đề xuất của bạn và hỗ trợ bàn đứng thiết lập doanh nghiệp địa phương trong môi trường làm việc của họ.",
        "teamDescription": "Cá nhân",
        "teamExperience": "Chưa có kinh nghiệm",
        "gender": "Global",
        "ageRange": [0, 90],
        "professional": ["Mọi người"],
        "geographical": ["Vietnam"],
        "behavior": "Các nghiên cứu khẳng định một cách dứt khoát rằng việc kết hợp bàn làm việc đứng vào thói quen làm việc tại nhà, dành 1 đến 2 giờ mỗi ngày, có thể giúp cải thiện lưu thông máu và hoạt động như một biện pháp phòng ngừa chứng đau lưng. Điều này phù hợp với nhu cầu cấp thiết về các giải pháp công thái học để chống lại tính chất ít vận động của công việc từ xa.",
        "apps": "Không có thông tin",
        "outstand": ["Ứng dụng cao"],
        "currentDev": "[Alpha] Ý tưởng đang được thử nghiệm trong môi trường thực tế nhưng chưa hoàn thiện",
        "support": "",
        "innovator_id": "65f4602b14c88ec7dd8dd787",
        "files": []
    },
    {
        "name": "Túi sản xuất tái sử dụng",
        "domain": ["Hàng tiêu dùng (Consumer Goods)"],
        "slogan": "Học sinh làm được, bạn cũng thế",
        "problem": "Năm 2012, Elif Bilgin, 16 tuổi, đã giành được giải thưởng Khoa học Mỹ sau khi cô phát hiện ra rằng túi nhựa hàng ngày có thể được thay thế hoàn toàn bằng túi làm từ vỏ chuối. Cách đây vài năm, một sinh viên người Brazil đã tìm ra khả năng tạo ra những chiếc túi có thể phân hủy sinh học từ vỏ cam.",
        "solution": "Quyết định loại vật liệu tái chế nào bạn muốn tạo ra những chiếc túi có thể tái sử dụng của mình. Kết nối với các công ty hoặc nhà máy địa phương nơi bạn có thể tìm thấy loại vật liệu tái chế đã chọn, thường là miễn phí. Tạo một thiết kế cho chiếc túi của bạn, xây dựng thương hiệu cho công ty của bạn, sau đó tạo chiếc túi đầu tiên của bạn. Tiếp thị đến khu vực địa phương của bạn hoặc thông qua cửa hàng trực tuyến của bạn.",
        "teamDescription": "Cá nhân",
        "teamExperience": "Chưa có kinh nghiệm",
        "gender": "Global",
        "ageRange": [0, 90],
        "professional": ["Mọi người"],
        "geographical": ["Vietnam"],
        "behavior": "Nếu bạn không muốn tạo ra những chiếc túi của mình, bạn có thể liên hệ với một nhà máy hoặc công ty hiện có đang sản xuất những chiếc túi có thể tái sử dụng. Trở thành một chi nhánh hoặc đại lý bán hàng cho sản phẩm của họ.",
        "apps": "Không có thông tin",
        "outstand": ["Ứng dụng cao"],
        "currentDev": "[Alpha] Ý tưởng đang được thử nghiệm trong môi trường thực tế nhưng chưa hoàn thiện",
        "support": "",
        "innovator_id": "65f4602b14c88ec7dd8dd787",
        "files": []
    },
    {
        "name": "Bàn chải đánh răng tre",
        "domain": ["Hàng tiêu dùng (Consumer Goods)"],
        "slogan": "Học sinh làm được, bạn cũng thế",
        "problem": "Với rất nhiều áp lực đặt lên môi trường của chúng ta, ngày càng có nhiều ý tưởng khởi nghiệp sáng tạo xuất hiện đối với các sản phẩm chúng ta sử dụng hàng ngày. Một trong số đó là bàn chải đánh răng bằng tre.",
        "solution": "Cách thực hiện: Tự thiết kế hoặc kết nối với nhà sản xuất bàn chải đánh răng bằng tre. Thiết lập một trang web cho sản phẩm của bạn và quyết định xem bạn có bán hàng tại địa phương hay không. Nếu bạn chọn bán hàng tại địa phương, khả năng là vô tận. Kết nối với các siêu thị địa phương và hỏi người quản lý xem họ có quan tâm đến hợp đồng đôi bên cùng có lợi với bạn bằng cách cung cấp cho họ bàn chải đánh răng thân thiện với môi trường, được sản xuất tại địa phương hay không. Bạn cũng có thể thiết lập một gian hàng hàng tuần tại chợ địa phương để bán cọ của mình.",
        "teamDescription": "Cá nhân",
        "teamExperience": "Chưa có kinh nghiệm",
        "gender": "Global",
        "ageRange": [0, 90],
        "professional": ["Mọi người"],
        "geographical": ["Vietnam"],
        "behavior": "Những bàn chải này có thể được thiết kế bởi chính bạn nếu bạn muốn đổi mới và tạo ra bàn chải của riêng mình hoặc bằng cách kết nối với nhà sản xuất. Một số nhà sản xuất thậm chí còn cung cấp nhãn màu trắng, nghĩa là bạn có thể thêm nhãn hiệu cá nhân của mình vào cọ họ sản xuất.",
        "apps": "Không có thông tin",
        "outstand": ["Ứng dụng cao"],
        "currentDev": "[Alpha] Ý tưởng đang được thử nghiệm trong môi trường thực tế nhưng chưa hoàn thiện",
        "support": "",
        "innovator_id": "65f4602b14c88ec7dd8dd787",
        "files": []
    },
]


contest_data = [
    {
        "name": "Học tập kỷ nguyên 4.0",
        "topic": "Học tập",
        "location": "Thành phố Hồ Chí Minh",
        "otherInfo": "",
        "prize1": "Giải nhất",
        "prize1Value": "1000",
        "prize1Quantity": "1",
        "prize2": "Giải nhì",
        "prize2Value": "500",
        "prize2Quantity": "3",
        "prize3": "Giải ba",
        "prize3Value": "300",
        "prize3Quantity": "5",
        "round1": "Vòng sơ loại",
        "roundType1": "upload",
        "scoringType1": "vote",
        "time1": {"start": "2024-07-01T00:00:00Z", "end": "2024-07-07T00:00:00Z"},
        "round2": "Vòng chung kết",
        "roundType2": "online",
        "scoringType2": "mark",
        "time2": {"start": "2024-07-08T00:00:00Z", "end": "2024-07-14T00:00:00Z"},
        "description": "Cuộc thi học tập kỷ nguyên 4.0",
        "submission_list": [
            {
                "idea_id": "656085987981d95b28f942a7",
            },
            {
                "idea_id": "6564a727fe8eec62f4140b48",
            },
            {
                "idea_id": "657359ccf7604b2675a6eb9c",
            },
            {
                "idea_id": "6573f4138276323dd10d84ce",
            },
        ],
    },
    {
        "name": "Viết về thầy cô",
        "topic": "Văn học",
        "location": "Hà Nội",
        "otherInfo": "Dành cho học sinh THPT",
        "prize1": "Giải nhất",
        "prize1Value": "1000",
        "prize1Quantity": "1",
        "prize2": "Giải nhì",
        "prize2Value": "500",
        "prize2Quantity": "2",
        "prize3": "Giải ba",
        "prize3Value": "300",
        "prize3Quantity": "3",
        "round1": "Vòng sơ loại",
        "roundType1": "upload",
        "scoringType1": "vote",
        "time1": {"start": "2024-06-01T00:00:00Z", "end": "2024-06-10T00:00:00Z"},
        "round2": "Vòng chung kết",
        "roundType2": "offline",
        "scoringType2": "mark",
        "time2": {"start": "2024-06-20T00:00:00Z", "end": "2024-06-25T00:00:00Z"},
        "description": "Cuộc thi viết về thầy cô giáo",
    },
    {
        "name": "Khám phá khoa học",
        "topic": "Khoa học kỹ thuật",
        "location": "Đà Nẵng",
        "otherInfo": "Dành cho học sinh THCS",
        "prize1": "Giải nhất",
        "prize1Value": "750",
        "prize1Quantity": "1",
        "prize2": "Giải nhì",
        "prize2Value": "500",
        "prize2Quantity": "2",
        "prize3": "Giải ba",
        "prize3Value": "300",
        "prize3Quantity": "3",
        "round1": "Vòng loại",
        "roundType1": "upload",
        "scoringType1": "mark",
        "time1": {"start": "2024-07-01T00:00:00Z", "end": "2024-07-10T00:00:00Z"},
        "round2": "Vòng chung kết",
        "roundType2": "offline",
        "scoringType2": "mark",
        "time2": {"start": "2024-07-20T00:00:00Z", "end": "2024-07-25T00:00:00Z"},
        "description": "Cuộc thi khám phá khoa học dành cho học sinh THCS",
    },
    {
        "name": "Sáng tạo thời trang",
        "topic": "Nghệ thuật",
        "location": "TP. Hồ Chí Minh",
        "otherInfo": "Dành cho sinh viên",
        "prize1": "Giải nhất",
        "prize1Value": "2000",
        "prize1Quantity": "1",
        "prize2": "Giải nhì",
        "prize2Value": "1000",
        "prize2Quantity": "2",
        "prize3": "Giải ba",
        "prize3Value": "500",
        "prize3Quantity": "3",
        "round1": "Vòng sơ loại",
        "roundType1": "upload",
        "scoringType1": "vote",
        "time1": {"start": "2024-08-01T00:00:00Z", "end": "2024-08-10T00:00:00Z"},
        "round2": "Vòng chung kết",
        "roundType2": "offline",
        "scoringType2": "mark",
        "time2": {"start": "2024-08-20T00:00:00Z", "end": "2024-08-25T00:00:00Z"},
        "description": "Cuộc thi sáng tạo thời trang dành cho sinh viên",
    },
    {
        "name": "Viết về quê hương",
        "topic": "Văn học",
        "location": "Huế",
        "otherInfo": "Dành cho mọi lứa tuổi",
        "prize1": "Giải nhất",
        "prize1Value": "1000",
        "prize1Quantity": "1",
        "prize2": "Giải nhì",
        "prize2Value": "500",
        "prize2Quantity": "2",
        "prize3": "Giải ba",
        "prize3Value": "300",
        "prize3Quantity": "3",
        "round1": "Vòng sơ loại",
        "roundType1": "upload",
        "scoringType1": "vote",
        "time1": {"start": "2024-09-01T00:00:00Z", "end": "2024-09-10T00:00:00Z"},
        "round2": "Vòng chung kết",
        "roundType2": "offline",
        "scoringType2": "mark",
        "time2": {"start": "2024-09-20T00:00:00Z", "end": "2024-09-25T00:00:00Z"},
        "description": "Cuộc thi viết về quê hương",
    },
    {
        "name": "Tài năng âm nhạc",
        "topic": "Nghệ thuật",
        "location": "Quảng Ninh",
        "otherInfo": "Dành cho mọi lứa tuổi",
        "prize1": "Giải nhất",
        "prize1Value": "1500",
        "prize1Quantity": "1",
        "prize2": "Giải nhì",
        "prize2Value": "750",
        "prize2Quantity": "2",
        "prize3": "Giải ba",
        "prize3Value": "500",
        "prize3Quantity": "3",
        "round1": "Vòng loại",
        "roundType1": "upload",
        "scoringType1": "vote",
        "time1": {"start": "2024-10-01T00:00:00Z", "end": "2024-10-10T00:00:00Z"},
        "round2": "Vòng chung kết",
        "roundType2": "offline",
        "scoringType2": "mark",
        "time2": {"start": "2024-10-20T00:00:00Z", "end": "2024-10-25T00:00:00Z"},
        "description": "Cuộc thi tài năng âm nhạc",
    },
    {
        "name": "Viết về cuộc sống",
        "topic": "Văn học",
        "location": "Hà Nội",
        "otherInfo": "Dành cho mọi lứa tuổi",
        "prize1": "Giải nhất",
        "prize1Value": "1000",
        "prize1Quantity": "1",
        "prize2": "Giải nhì",
        "prize2Value": "500",
        "prize2Quantity": "2",
        "prize3": "Giải ba",
        "prize3Value": "300",
        "prize3Quantity": "3",
        "round1": "Vòng sơ loại",
        "roundType1": "upload",
        "scoringType1": "vote",
        "time1": {"start": "2024-11-01T00:00:00Z", "end": "2024-11-10T00:00:00Z"},
        "round2": "Vòng chung kết",
        "roundType2": "offline",
        "scoringType2": "mark",
        "time2": {"start": "2024-11-20T00:00:00Z", "end": "2024-11-25T00:00:00Z"},
        "description": "Cuộc thi viết về cuộc sống",
    },
    {
        "name": "Khám phá khoa học",
        "topic": "Khoa học kỹ thuật",
        "location": "Đà Nẵng",
        "otherInfo": "Dành cho học sinh THCS",
        "prize1": "Giải nhất",
        "prize1Value": "750",
        "prize1Quantity": "1",
        "prize2": "Giải nhì",
        "prize2Value": "500",
        "prize2Quantity": "2",
        "prize3": "Giải ba",
        "prize3Value": "300",
        "prize3Quantity": "3",
        "round1": "Vòng loại",
        "roundType1": "upload",
        "scoringType1": "mark",
        "time1": {"start": "2024-12-01T00:00:00Z", "end": "2024-12-10T00:00:00Z"},
        "round2": "Vòng chung kết",
        "roundType2": "offline",
        "scoringType2": "mark",
        "time2": {"start": "2024-12-20T00:00:00Z", "end": "2024-12-25T00:00:00Z"},
        "description": "Cuộc thi khám phá khoa học dành cho học sinh THCS",
    },
    {
        "name": "Sáng tạo thời trang",
        "topic": "Nghệ thuật",
        "location": "TP. Hồ Chí Minh",
        "otherInfo": "Dành cho sinh viên",
        "prize1": "Giải nhất",
        "prize1Value": "2000",
        "prize1Quantity": "1",
        "prize2": "Giải nhì",
        "prize2Value": "1000",
        "prize2Quantity": "2",
        "prize3": "Giải ba",
        "prize3Value": "500",
        "prize3Quantity": "3",
        "round1": "Vòng sơ loại",
        "roundType1": "upload",
        "scoringType1": "vote",
        "time1": {"start": "2024-01-01T00:00:00Z", "end": "2024-01-10T00:00:00Z"},
        "round2": "Vòng chung kết",
        "roundType2": "offline",
        "scoringType2": "mark",
        "time2": {"start": "2024-01-20T00:00:00Z", "end": "2024-01-25T00:00:00Z"},
        "description": "Cuộc thi sáng tạo thời trang dành cho sinh viên",
    },
    {
        "name": "Viết về quê hương",
        "topic": "Văn học",
        "location": "Huế",
        "otherInfo": "Dành cho mọi lứa tuổi",
        "prize1": "Giải nhất",
        "prize1Value": "1000",
        "prize1Quantity": "1",
        "prize2": "Giải nhì",
        "prize2Value": "500",
        "prize2Quantity": "2",
        "prize3": "Giải ba",
        "prize3Value": "300",
        "prize3Quantity": "3",
        "round1": "Vòng sơ loại",
        "roundType1": "upload",
        "scoringType1": "vote",
        "time1": {"start": "2024-02-01T00:00:00Z", "end": "2024-02-10T00:00:00Z"},
        "round2": "Vòng chung kết",
        "roundType2": "offline",
        "scoringType2": "mark",
        "time2": {"start": "2024-02-20T00:00:00Z", "end": "2024-02-25T00:00:00Z"},
        "description": "Cuộc thi viết về quê hương",
    },
    {
        "name": "Tài năng âm nhạc",
        "topic": "Nghệ thuật",
        "location": "Quảng Ninh",
        "otherInfo": "Dành cho mọi lứa tuổi",
        "prize1": "Giải nhất",
        "prize1Value": "1500",
        "prize1Quantity": "1",
        "prize2": "Giải nhì",
        "prize2Value": "750",
        "prize2Quantity": "2",
        "prize3": "Giải ba",
        "prize3Value": "500",
        "prize3Quantity": "3",
        "round1": "Vòng loại",
        "roundType1": "upload",
        "scoringType1": "vote",
        "time1": {"start": "2024-03-01T00:00:00Z", "end": "2024-03-10T00:00:00Z"},
        "round2": "Vòng chung kết",
        "roundType2": "offline",
        "scoringType2": "mark",
        "time2": {"start": "2024-03-20T00:00:00Z", "end": "2024-03-25T00:00:00Z"},
        "description": "Cuộc thi tài năng âm nhạc",
    },
]
