name: Push Docker Image to AWS ECR
on:
  push:
    branches: [main]

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  check-out: 
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
  login-to-ecr:
    runs-on: ubuntu-latest
    needs: check-out
    steps:
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      -
        name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
  build-n-push:
    needs: login-to-ecr
    runs-on: ubuntu-latest
    steps:
      -  
        name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: woridea
          IMAGE_TAG: latest
        run: |
          echo ls
          docker build -t ./backend/$REPOSITORY .
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
